import type { Metadata } from "next";
import { Raleway } from "next/font/google"; //change the font!
import "./globals.css";

const inter = Raleway({ subsets: ["latin"] }); // change the font!

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
